In [3]:

import numpy as np
# Creates an array that goes from 8 to 16 in 10 elements
np.linspace(8,16,10)

array([ 8.        ,  8.88888889,  9.77777778, 10.66666667, 11.55555556,
       12.44444444, 13.33333333, 14.22222222, 15.11111111, 16.        ])

In [1]:
import numpy as np

#Creates an array from 2 to 12 with 1 steps
np.arange(2,12)

##
import numpy as np

#Creates a matrix with all values initialized to 7, of size 5x6
np.full((5,6), 7)

array([[7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7]])

In [7]:
import numpy as np

a = np.arange(15)
a[:8:2]

array([0, 2, 4, 6])

![Matrix indexing](matrixIndex.png)

In [5]:
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-1, 2, 10000)

y = np.piecewise(x, [x < 0 or x > 1.5, 0 <= x < 1, 1 <= x <= 1.5], [0, lambda x: x, 1])

plt. plot(x,y)
plt.title('FUncion de densidad de probabilidad')
plt.show()

ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)